server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy no-referrer always;

    location /yowasp/ {
        add_header X-Content-Type-Options nosniff always;
        add_header Referrer-Policy no-referrer always;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        types {
            application/wasm wasm;
            application/javascript js;
            application/octet-stream tar;
        }
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
